version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/init:/docker-entrypoint-initdb.d/
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"